apiVersion: v1
kind: Service
metadata:
  name: my-devops-website-service
spec:
  selector:
    app: my-devops-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
